### ISSUE TITLE
Add auto-updating of Babel version

### ISSUE THREAD

**Issue by tmc** [jvatic/goja-babel#4]
Some GitHub action automation could add auto updating.

**Comment by psilva261** [comment]
Hi @tmc !

Here's a pull request with the current version: https://github.com/jvatic/goja-babel/pull/6 The standalone package has moved into the main babel project, it should be really just increasing the version numbers to update.

Philip

**Comment by tmc** [comment]
@psilva261 that PR looks great! Do you think you could extend that work (in a separate branch/PR) to consider how auto-updating to track upstream would work?

**Comment by psilva261** [comment]
Thanks! Yes maybe at some point, right now I'm not sure though how time-consuming this is to implement. But actually this could be fun to realize. FWIW I think this really depends on the other issue #5 that you created. I mean there are already unit tests transforming code which seem to cover the main branches of execution but it would be nice to have more confidence in transformation of more complex code. (Also I wouldn't expect babel to always create the same code. So probably it would be necessary to run the resulting code with goja runtime) Would you be up for adding a 1 or 2 tests with more complex examples?

**Comment by jvatic** [comment]
@psilva261 I think modifying the existing test to run the transformed code in goja and assert on the output should be enough to have confidence (will require the test program to have a meaningful output and I'm open to this having a bit of complexity, and adding a jsx tranform would add some confidence the code is being transformed with this change).

I'll try and find some time soon to setup CI, and a GitHub action to automatically bump the version for each babel release.
